Web-UI/Models/Navbar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Web_UI.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }
}

Web-UI/Controllers/NavbarController.cs
using Web_UI.Domain;
using Web_UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web_UI.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Data();
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

Web-UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>PMS</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!-- DataTables CSS -->
    <link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
    <!-- DataTables Responsive CSS -->
    <link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

    <link href="@Url.Content("~/bower_components/morrisjs/morris.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Main.css")" rel="stylesheet" type="text/css" /> <!-- Custom CSS -->

    <!-- jQuery -->
    @*@Scripts.Render("~/bundles/jquery")*@
    <script src="~/Scripts/jquery-1.6.4.js"></script>

    <script src="@Url.Content("~/bower_components/jquery/dist/jquery.min.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>

    <!-- SignalR -->
    @RenderSection("signalr", required: false)

</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        @Html.Action("Index", "Navbar")

        <div id="page-wrapper">
            @RenderBody()
            
        </div>
        <!-- /#page-wrapper -->
        
    </div>
    <!-- /#wrapper -->
    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/raphael/raphael-min.js")"></script>

    <!-- DataTables JavaScript -->
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>

    <!-- Custom Theme JavaScript -->
    <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>

    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    @RenderSection("scripts", required: false)
</body>
</html>

Web-UI/Views/Shared/_Navbar.cshtml
@model IEnumerable<Web_UI.Models.Navbar>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        @Html.ActionLink("PMS", "Index", new { controller = "Home" }, new { @class = "navbar-brand" })
    </div>
    <!-- /.navbar-header -->
    
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                
                @foreach (var item in Model)
                {
                    if (item.isParent == false && item.parentId == 0)
                    {
                        <li><a href="@Url.Action(item.action, item.controller)"><i class="@item.imageClass"></i> @item.nameOption</a></li>
                    }
                    else
                    {
                        if (item.isParent == true)
                        {
                            <li>
                                <a href="#"><i class="@item.imageClass"></i> @item.nameOption<span class="fa arrow"></span></a>                          
                                <ul class="nav nav-second-level">
                                    @foreach (var child in Model.Where(p => p.parentId == item.Id))
                                    {
                                        if (child.controller == null)
                                        {
                                            <li><a href="#">@child.nameOption</a></li>
                                        }
                                        else
                                        {
                                        <li><a href="@Url.Action(child.action, child.controller)">@child.nameOption</a></li>
                                        }
                                    }
                                </ul>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>